
services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: app_user
      DATABASE_PASSWORD: app_password
      DATABASE_NAME: app_database
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db_data:
